spring:
  application:
    name: blog

  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  sql:
#    init:
#      mode: always  # ✅ `data.sql` 실행 강제
