name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          # 원하는 형식 (예: 2025-03-28T10-17-48)
          format: YYYY-MM-DDTHH-mm-ss
          # UTC+9 기준
          utcOffset: "+09:00"

      # ─────────────────────────────────────────────────────────
      # 빌드 결과를 찾아서 artifact 라는 ENV 에 JAR "파일명"만 저장
      # ─────────────────────────────────────────────────────────
      - name: Set artifact
        run: |
          # ./build/libs/*.jar 에서 첫 번째(가장 먼저 찾은) 파일만 추출
          jar_file=$(ls ./build/libs/*.jar | head -n1)
          # 전체 경로 중에서 파일명만 추출 (예: blog-0.0.1-SNAPSHOT.jar)
          jar_name=$(basename "$jar_file")
          # GitHub Actions 환경 변수에 저장
          echo "artifact=$jar_name" >> $GITHUB_ENV

      # ─────────────────────────────────────────────────────────
      # Elastic Beanstalk 배포
      # ─────────────────────────────────────────────────────────
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: spring-boot-developer
          environment_name: SpringBootDeveloper-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          # 실제 배포 경로에서 ./build/libs/ + 파일명을 합쳐 완전한 경로로 지정
          deployment_package: ./build/libs/${{ env.artifact }}
